services:
  master:
    build:
      context: .
      dockerfile: master/Dockerfile
    container_name: master
    ports:
      - "8000:8000"
    environment:
      - SECONDARY_URLS=${SECONDARY_URLS}
      - RETRY_COUNT=${RETRY_COUNT}
      - RETRY_DELAY=${RETRY_DELAY}
      - REPLICATE_SECRET=${REPLICATE_SECRET}
    depends_on:
      - secondary1
      - secondary2
    networks:
      - lognet

  secondary1:
    build:
      context: .
      dockerfile: secondary/Dockerfile
    container_name: secondary1
    ports:
      - "8001:8000"
    environment:
      - MAX_REPLICATION_DELAY=${MAX_REPLICATION_DELAY}
      - REPLICATE_SECRET=${REPLICATE_SECRET}
    networks:
      - lognet

  secondary2:
    build:
      context: .
      dockerfile: secondary/Dockerfile
    container_name: secondary2
    ports:
      - "8002:8000"
    environment:
      - MAX_REPLICATION_DELAY=${MAX_REPLICATION_DELAY}
      - REPLICATE_SECRET=${REPLICATE_SECRET}
    networks:
      - lognet

networks:
  lognet:
    driver: bridge
