services:
  master:
    build:
      context: .
      dockerfile: master/Dockerfile
    container_name: master
    ports:
      - "8000:8000"
    environment:
      - SECONDARY_URLS=${SECONDARY_URLS}
      - INITIAL_RETRY_DELAY=${INITIAL_RETRY_DELAY}
      - MAX_RETRY_DELAY=${MAX_RETRY_DELAY}
      - SECONDARY_AUTH_SECRET=${SECONDARY_AUTH_SECRET}
    depends_on:
      - secondary1
      - secondary2
    networks:
      - lognet

  secondary1:
    build:
      context: .
      dockerfile: secondary/Dockerfile
    container_name: secondary1
    ports:
      - "8001:8000"
    environment:
      - MAX_REPLICATION_DELAY=${MAX_REPLICATION_DELAY}
      - SECONDARY_AUTH_SECRET=${SECONDARY_AUTH_SECRET}
      - SECONDARY_ERROR_PROBABILITY=${SECONDARY_ERROR_PROBABILITY}
    networks:
      - lognet

  secondary2:
    build:
      context: .
      dockerfile: secondary/Dockerfile
    container_name: secondary2
    ports:
      - "8002:8000"
    environment:
      - MAX_REPLICATION_DELAY=${MAX_REPLICATION_DELAY}
      - REPLICATE_SECRET=${REPLICATE_SECRET}
      - SECONDARY_ERROR_PROBABILITY=${SECONDARY_ERROR_PROBABILITY}
    networks:
      - lognet

networks:
  lognet:
    driver: bridge
